[package]
name = "minitito-gui"
version = "0.1.0"
edition = "2021"

[dependencies]

egui = "0.20.1"         # GUI
egui_extras = "0.20.0"  # GUI
eframe = "0.20.1"       # GUI

open = "3.2.0"          # web links

[build-dependencies]
cc = "1.0"              # Compile C