name: CI

on:
  push:
    branches: '**'
    paths:
    - "src/**"
    - "Cargo.toml"
    - "programs/tests"
  pull_request:
    branches: '**'
    paths:
    - "src/**"
    - "Cargo.toml"
    - "programs/tests"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update && sudo apt install libgtk-3-dev libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Unit tests
      run: cargo test --verbose
