name: Release test

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update && sudo apt install libgtk-3-dev
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "target/x86_64-unknown-linux-gnu/release/titomachine"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
